server:
  port: 8080

spring:
  application:
    name: pub-sub-service

  config:
    import: /etc/secrets/secret.properties
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

# remove this line if u want .sql file to be processed
  sql:
    init:
      mode: never

  datasource:
    url: ${db.url}
    # for h2 jdbc:h2:mem:testdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    #for h2 org.h2.Driver
    username: ${db.username}
    #for h2 sa
    password: ${db.password}
      #for h2 no password

    jpa:
      hibernate:
        ddl-auto: none # don't auto-create tables if using schema.sql
      show-sql: true
      database-platform:  org.hibernate.dialect.MySQL8Dialect
      #for h2 org.hibernate.dialect.H2Dialect
      properties:
        hibernate:
          format_sql: true