#prod enable by:->  java -Dspring.profiles.active=prod -jar your-app.jar

server:
  port: 8080

spring:
  application:
    name: pub-sub-service

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

# remove this line if u want .sql file to be processed
  sql:
    init:
      mode: never

  datasource:
    url: jdbc:mysql://localhost:3306/pubsub_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: kumar9905

    jpa:
      hibernate:
        ddl-auto: none # don't auto-create tables if using schema.sql
      show-sql: false
      open-in-view: false
      database-platform:  org.hibernate.dialect.MySQL8Dialect
      properties:
        hibernate:
          format_sql: true