name: Build and Deploy Spring Boot App to Render

on:
  push:
    branches: [ main ]  # You can change this to "master" or other branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'  # OpenJDK from Eclipse Foundation

      - name: Set up Maven
        run: sudo apt-get install -y maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

#      - name: Upload JAR Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: app-jar
#          path: target/*.jar  as we are trigger dockerfile below, so no need to upload jar

      - name: Trigger Render Deploy
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}